# Generated by Django 3.1.5 on 2021-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cprice', models.IntegerField()),
                ('ctag', models.TextField()),
                ('cimg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
